"""empty message

Revision ID: 9365c1b4d1ac
Revises: 
Create Date: 2019-11-04 22:48:55.800620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9365c1b4d1ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tree', sa.JSON(none_as_null=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_trees')
    # ### end Alembic commands ###
